name: Docker

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "tobiaswild" --password-stdin
        docker image build -t tobiaswild/domain-connect-dyndns:latest .
        docker push tobiaswild/domain-connect-dyndns:latest
